version: '3'
services:
  spark-master:
    image: spark
    environment:
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
    command: bin/spark-class org.apache.spark.deploy.master.Master
    ports:
      - '8080:8080'
      - '7077:7077'
      - '4041:4040'
    networks:
      - spark-network

  spark-worker1:
    image: spark
    environment:
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
    command: bin/spark-class org.apache.spark.deploy.worker.Worker spark://spark-master:7077
    networks:
      - spark-network

  spark-worker2:
    image: spark
    environment:
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
    command: bin/spark-class org.apache.spark.deploy.worker.Worker spark://spark-master:7077
    networks:
      - spark-network

  jupyter-spark:
    image: jupyter/pyspark-notebook:spark-3.4.0
    environment:
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      - SPARK_OPTS=--master spark://spark-master:7077
    ports:
      - '8888:8888'
      - '4040:4040'
    volumes:
      - ./notebooks:/home/jovyan/work
    networks:
      - spark-network

networks:
  spark-network:
    driver: bridge
