version: '3'
services:
  spark-master:
    image: bde2020/spark-master:3.3.0-hadoop3.3
    environment:
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
    command: /bin/bash -c "/spark/bin/spark-class org.apache.spark.deploy.master.Master -h spark-master"
    ports:
      - '8080:8080'
      - '7077:7077'
      - '4041:4040'
    networks:
      - spark-net

  spark-worker-1:
    image: bde2020/spark-worker:3.3.0-hadoop3.3
    environment:
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
    command: /bin/bash -c "/spark/bin/spark-class org.apache.spark.deploy.worker.Worker -h spark-worker-1 spark://spark-master:7077"
    ports:
      - '4042:4040'
    networks:
      - spark-net

  spark-worker-2:
    image: bde2020/spark-worker:3.3.0-hadoop3.3
    environment:
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
    command: /bin/bash -c "/spark/bin/spark-class org.apache.spark.deploy.worker.Worker -h spark-worker-2 spark://spark-master:7077"
    ports:
      - '4043:4040'
    networks:
      - spark-net

  jupyter-spark:
    image: jupyter/pyspark-notebook:python-3.7
    environment:
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      - SPARK_OPTS=--master spark://spark-master:7077
    ports:
      - '8888:8888'
      - '4040:4040'
    volumes:
      - ./notebooks:/home/jovyan/work
    networks:
      - spark-net

networks:
  spark-net:
    driver: bridge
